---
# This workflow will install Python dependencies, run tests

name: Run CI/CD

on: push

env:
  PYPI_REPO_URL: https://test.pypi.org/legacy/
  out_dir: "dist/"

jobs:
  build-n-publish:
    name: Build and upload release to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    permissions:
      actions: read
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Install pypa/build
        shell: bash
        run: |
          python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        shell: bash
        run: python -m build --sdist --wheel --outdir ${{ env.out_dir }}

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: ${{ env.out_dir }}

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ env.PYPI_REPO_URL }}
          verbose: 'true'
